name: Build and Release Python App for Windows

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller --onefile --windowed --name snake main.py

      - name: Get version (timestamp)
        id: version
        run: echo "version=$(date +'%Y.%m.%d.%H%M%S')" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.version }}
          name: "Release v${{ env.version }}"
          draft: false
          prerelease: false
          files: dist/snake.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
